### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [martvaso/codecademy_python_projects#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4
* _Comment(s):_ The coding was concise, robust and returns the required results.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4
* _Comment(s):_ Project Requirements were executed without any errors or issues.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4
* _Comment(s):_ The architecture and modular setup of code was on point. Not sure what this import was for `import re`
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4
* _Comment(s):_  Great use of standard python language features. Great use of super and interpolation. Also good job explicitly declaring variables. 
 
### Overall Score: 16/16

Great job. No errors were detected. Very nice testing your code too.

**Comment by martvaso** [comment]
Regarding 'import re' - it's just for email validation which I decided to implement using a regular expression.

Thanks for your feedback!

**Comment by mp1pro** [comment]
I see, Nice job exceeding the expectations
